name: Build WSL2 Kernel

on:
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  
    steps:
      - name: Checkout Repository (Config)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  
          path: config-repo  

      - name: Checkout WSL2 Kernel Source
        uses: actions/checkout@v4
        with:
          repository: microsoft/WSL2-Linux-Kernel
          ref: linux-msft-wsl-6.6.y  
          fetch-depth: 1  
          path: WSL2-Linux-Kernel  

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential flex bison dwarves libssl-dev libelf-dev bc python3 pahole cpio qemu-utils 7zip

      - name: Generate Custom Config
        run: |
          cd WSL2-Linux-Kernel/
          cp Microsoft/config-wsl Microsoft/config-wsl-custom
          cat ../config-repo/part.txt >> Microsoft/config-wsl-custom
          make olddefconfig KCONFIG_CONFIG=Microsoft/config-wsl-custom
          ls -l Microsoft/config-wsl-custom  

      - name: Build Kernel
        run: |
          cd WSL2-Linux-Kernel/
          make -j$(nproc) KCONFIG_CONFIG=Microsoft/config-wsl-custom

      - name: Install Modules
        run: |
          cd WSL2-Linux-Kernel/
          make INSTALL_MOD_PATH="$PWD/modules" modules_install KCONFIG_CONFIG=Microsoft/config-wsl-custom
          sudo ./Microsoft/scripts/gen_modules_vhdx.sh "$PWD/modules" $(make -s kernelrelease) modules.vhdx
          
      - name: Compress Artifacts
        run: |
          cd WSL2-Linux-Kernel/
          7z a -mx=9 modules.vhdx.7z modules.vhdx  
          7z a -mx=9 arch/x86/boot/bzImage.7z arch/x86/boot/bzImage
          ls -lh modules.vhdx.7z arch/x86/boot/bzImage.7z  
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_id }}-wsl2-kernel
          name: WSL2 Kernel Build ${{ github.run_id }}
          body: |
            WSL2 Kernel build with custom config from part.txt
            Commit: ${{ github.sha }}
            Repository Branch: ${{ github.ref_name }}
            WSL2 Kernel Source Branch: linux-msft-wsl-6.6.y
            Note: Assets are compressed as .7z files. Use 7-Zip (or `7z x` on Linux) to decompress before use.
          files: |
            WSL2-Linux-Kernel/modules.vhdx.7z
            WSL2-Linux-Kernel/arch/x86/boot/bzImage.7z
